### PR TITLE
Added improvements at creating a new address and prove of work

### PR DESCRIPTION
**Pull request by Pineapple6**

### CODE REVIEW

**Comment by cosme12** [comment]
@Pineapple6 now it has conflict. You will have to save your changes. Pull the branch again and apply the changes manually. Sorry for being annoying 😬

**Comment by Pineapple6** [comment]
I'm trying to solve the conflict, sorry for all the reopen and close 😅

**Comment by Pineapple6** [comment]
Ok, It's ready.

**Comment by Pineapple6** [comment]
I don't exactly know.
Obviously, if the proof of work is more complex it's code will be also more complex.
If you want it, I can send a pull request only with the adding an address changes and try to optimize the code in the proof of work.

**Comment by cosme12** [comment]
if it's not much hassle, send the "new address to text file" commits in pull request, so we can accept that. And then we keep thinking what to do with the proof of work.

**Comment by Pineapple6** [comment]
Ok. I can't do it right now, but tomorrow I'll do what you say :+1:

**Pull request closed without merging**
