### PR TITLE
Added improvements at creating adress and new proof of work

### PR DESCRIPTION
**Pull request by Pineapple6**
Now when you create your new address the keys are saved in a .txt file, in which you can copy/paste your direction and save it securely.

### CODE REVIEW

**Comment by Pineapple6** [comment]
For now i have implemented the new pow without adding previous block hash.
But i'll try to do it

**Comment by Pineapple6** [comment]
Ok, done! 😄 @kennethgoodman

**Comment by cosme12** [comment]
Ok guys, lets do this the right way. I just created a new branch called [v1.1.0](https://github.com/cosme12/SimpleCoin/tree/v1.1.0). Lets push everything there, so we can test big changes without messing with the Master (we want other people to still be able to run it without problems).
Then try to divide your pull request in as many pieces as possible. For example, typos should be in a pull request while saving keys to text file in another. This way we can accept the typos commit fast and focus on the real changes.
And last, keep it really simple.

BTW thanks for helping 👍

**Comment by Pineapple6** [comment]
Ok, I've made a new pull request to the new branch, I'll delete this one.

**Pull request closed without merging**
