### PR TITLE
Running miner.py in wallet.py

### PR DESCRIPTION
**Pull request by mehanalavimajd**
After this Pr the user don't need to run miner.py in another terminal

### CODE REVIEW

**Comment by mehanalavimajd** [comment]
No one will anwser me ?

**Comment by cosme12** [comment]
> No one will anwser me ?

Be patient. I will be looking at it as soon as I can. It's still weekend 😬

**Comment by mehanalavimajd** [comment]
Ok. Sorry

**Comment by cosme12** [comment]
Hey @mehanalavimajd , I tried your pull request but I found a little problem. If we execute the `miner.py` script there, the terminal starts running the miner and we lose access to the wallet code we were running in the beggining.
You probably have 2 options here: think another way of starting `miner.py` (if it's not already running) or use exceptions to display a message saying something like: "there are no nodes running".
Keep researching and good job!

As an extra note: when importing `os`, use `import os`. So when we call `os.system` and the code becomes to long we know to which module it belongs.

**Comment by mehanalavimajd** [comment]
Ok . I will try to fix it 😉

**Pull request closed without merging**
