### PR TITLE
Improvements to wallet.py

### PR DESCRIPTION
**Pull request by Aareon**
Supersedes https://github.com/cosme12/SimpleCoin/pull/25

- Removed f-string to retain comptability with Python versions < 3.6. 
- Added use of context manager when opening, writing, and closing the file.
- Removed the `welcome_msg` function and moved it’s content into the main conditional.
- Replaced `if response in int:` conditions with `if response == int:`

### CODE REVIEW

**Comment by Aareon** [comment]
I’ll officially test these changes today. For the time being, do not merge.

**Comment by cosme12** [comment]
Hey, I tested it and there are some little bugs, but overall seems to be a good idea. I'm going to add your pull request and then fix the little problems. Thanks for the help!

**Comment by Aareon** [comment]
What issues have you had, btw?

**Comment by cosme12** [comment]
There were a few missing ´´´)´´´ and a syntax error. But nothing big.

**Comment by Aareon** [comment]
Awesome. Good to hear. I believe with this PR, #25 can be closed

**Pull request merged**
